---
- name: Setup WireGuard Server
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  
  tasks:
    - name: Upgrade OS
      include_tasks: task-os_upgrade.yaml
      when: ansible_os_family == "Debian"

